### ISSUE TITLE
Resources$NotFoundException while starting the sample app

### ISSUE THREAD

**Issue by bakikocak** [pedrovgs/DraggablePanel#120]
I have downloaded the code and tried to run sample app. I was not able to run it as I got the message below. I tried clean and rebuild since it was suggested on several pages but did not work out. Any help appreciated. Thanks.

Note that `MainActivity.java:35` refers to `setContentView(R.layout.activity_main);` 

The error i got:

`05-17 16:48:36.458 17498-17498/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.github.pedrovgs.sample, PID: 17498
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.pedrovgs.sample/com.github.pedrovgs.sample.activity.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f020089
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f020089
                                                       at android.content.res.Resources.getValue(Resources.java:1401)
                                                       at android.content.res.Resources.getDrawable(Resources.java:831)
                                                       at android.content.Context.getDrawable(Context.java:458)
                                                       at com.android.internal.widget.ActionBarView.setIcon(ActionBarView.java:677)
                                                       at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:735)
                                                       at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1689)
                                                       at android.app.Activity.initWindowDecorActionBar(Activity.java:2157)
                                                       at android.app.Activity.setContentView(Activity.java:2172)
                                                       at com.github.pedrovgs.sample.activity.MainActivity.onCreate(MainActivity.java:35)
                                                       at android.app.Activity.performCreate(Activity.java:6272)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) `

**Comment by bakikocak** [comment]
I am able to install and run the sample app by typing following command in Android Studio:
./gradlew installDebug
