### ISSUE TITLE
DraggablePanel using resize transformer does not support landscape mode.

### ISSUE THREAD

**Issue by Amritpal33** [pedrovgs/DraggablePanel#22]
Hi,
   I am trying to show my DraggablePanel videoView in Landscape mode,but is not covering the even half the screen instead it just rotates the TopView with same dimensions.

Please look into the issue.

**Comment by Amritpal33** [comment]
Hi Pedrovgs,
    I am using your library in one of the high scale commercial Application.

Could you please help me resolving how can i support both resizing and Landscape mode.
Also the Bottom fragment gets overlapped to topFragment.

Your support will be highly appreciated.

Thanks.

**Comment by pedrovgs** [comment]
I can't right now because I'm working in other projects, sorry. Can you upload some screenshots with your problems. The VideoView problem in landscape is already know but I can't reproduce the other problem :S.

**Comment by Fiddl3** [comment]
check my fork:
https://github.com/Fiddl3/DraggablePanel/commit/c91dde454434a31f6e87a0794cd2212245c9bfa7

I tested the library in my application, but you need to test this yourself 

if you target pre KitKat devices (API < 16) you need to handle window flags in activity

``` java
    @Override
    public void onConfigurationChanged(final Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.JELLY_BEAN){
            if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
                getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
                getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
            } else {
                getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
            }
        }
    }
```

**Comment by Amritpal33** [comment]
Hi Fiddl3,
     Thanks alot for your Fixes. i tried to run your branch and the secondview issue and resizing is working perfectly.

How Landscape mode changing is Throwing Number Format Exception.Here are the Logs:

11-30 18:03:39.196: E/AndroidRuntime(12005): java.lang.NumberFormatException: Invalid float: ""
11-30 18:03:39.196: E/AndroidRuntime(12005):    at java.lang.StringToReal.invalidReal(StringToReal.java:63)
11-30 18:03:39.196: E/AndroidRuntime(12005):    at java.lang.StringToReal.parseFloat(StringToReal.java:289)
11-30 18:03:39.196: E/AndroidRuntime(12005):    at java.lang.Float.parseFloat(Float.java:300)
11-30 18:03:39.196: E/AndroidRuntime(12005):    at android.content.res.TypedArray.getFloat(TypedArray.java:288)
11-30 18:03:39.196: E/AndroidRuntime(12005):    at com.github.pedrovgs.DraggableView$1.onGlobalLayout(DraggableView.java:359)
11-30 18:03:39.196: E/AndroidRuntime(12005):    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:847)

Please check what could be done to fix this.

once Again Thanks alot.

**Comment by Fiddl3** [comment]
You are using DraggablePanel or DraggableView in your layout??
I'll look in to it tomorrow, and test in sample app.

**Comment by Amritpal33** [comment]
I am using Draggable Panel. i replace the value with hardcoded 2.0(random x scale factor and everything works fine.)

**Comment by pedrovgs** [comment]
@Fiddl3 are you going to send me a pull request?

**Comment by Fiddl3** [comment]
Tomorrow I'll work on this...
I'm going to remove part responsible for hiding status and nav bars, because it's depend on API level, ant can be confusing for developers.

Then I'll send pull request .

EDIT:
I'll add xml attribute for auto fullscreen mode.

**Comment by pedrovgs** [comment]
Please, update your branch with develop to avoid conflicts ;)

Thanks!

**Comment by pedrovgs** [comment]
I've also fixed one issue related with the horizontal drag effect. Review this branch if you need it: https://github.com/pedrovgs/DraggablePanel/tree/fix-horizontal-drag-problems

I'm going to integrate it once the reporter of the issue tell me it's working as expected.

**Comment by Fiddl3** [comment]
There will be one problem... 
In my version `scaleFactor` work differently. drag view is scaled to `1/scaleFactor` of its original size. now only for `scaleFactor=2` it match your calculations (In last commit I accidentally reverted changes in `scaleTransformer`).

This may be confusing for devs who use the library, but I think that this approach (for calculation) makes more sense (its more logical)

**Comment by pedrovgs** [comment]
Please, send me an email to pedrovicente.gomez@gmail.com with every detail to avoid retro compatibility problems and talk about this :)

I've also added one checkstyle configuration to the project and linked it to the travis CI build. Review this in your branch once be updated with development tip.

Thanks for your help!!!

**Comment by Fiddl3** [comment]
No problem.

I'll email you, but not today. 
There was a "small" party last night and... I can't think straight right now.

**Comment by Amritpal33** [comment]
Hi Fiddl3,
      I am constantly facing Number Format Exception while using DraggablePanel class in the following line:

float yScaleFactor = attributes.getFloat(R.styleable.draggable_view_top_view_y_scale_factor, DEFAULT_SCALE_FACTOR);

Here are the Logs:

12-01 11:48:40.502: E/AndroidRuntime(3621): java.lang.NumberFormatException: Invalid float: "48.0dip"
12-01 11:48:40.502: E/AndroidRuntime(3621):     at java.lang.StringToReal.invalidReal(StringToReal.java:63)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at java.lang.StringToReal.parseFloat(StringToReal.java:310)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at java.lang.Float.parseFloat(Float.java:300)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.content.res.TypedArray.getFloat(TypedArray.java:288)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at com.github.pedrovgs.DraggableView$1.onGlobalLayout(DraggableView.java:363)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:815)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1778)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.Choreographer.doFrame(Choreographer.java:544)
12-01 11:48:40.502: E/AndroidRuntime(3621):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)

Please Let me Know how can i fix this.

**Comment by Fiddl3** [comment]
draggable_view_top_view_y_scale_factor should be set as float value, not dimesion,

**Comment by dangalg** [comment]
I have fixed this in my branch but don't know how to share it with you

**Comment by Fiddl3** [comment]
I'm working on fullscreen support for ResizeTransformer on this branch: https://github.com/Fiddl3/DraggablePanel/tree/LanscapeMode-feature.
It's synchronized with `develop`, you can clone this branch and make your changes.

**Comment by dangalg** [comment]
I fixed the landscape problem... does anyone hear me?? Pedro?

**Comment by pedrovgs** [comment]
Hi @dangalg. If you have fixed the landscape problem, why don't you send me a pull request?

**Comment by dangalg** [comment]
I don't know how....

**Comment by pedrovgs** [comment]
Maybe you can start reading some articles about how github works http://readwrite.com/2013/09/30/understanding-github-a-journey-for-beginners-part-1

**Comment by dangalg** [comment]
I work with sourcetree and I am getting these errors when trying to create
a pull request:

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags
--set-upstream origin dangal:master
Pushing to https://dangalg@github.com/pedrovgs/DraggablePanel.git

remote: Permission to pedrovgs/DraggablePanel.git denied to dangalg.
fatal: unable to access '
https://dangalg@github.com/pedrovgs/DraggablePanel.git/': The requested URL
returned error: 403

Completed with errors, see above.

**Comment by pedrovgs** [comment]
That's normal, you are trying to push to my repository and you don't have permissions to do that. Review some articles about github and how to use it. You have to fork my project and clone your fork, not this repo. Change your repository code and then send me a pull request.

**Comment by dangalg** [comment]
ok fine, maybe I'll join fiddles branch because he is working on it as well

**Comment by vuhung3990** [comment]
hello, i have same problem when landscape it show a half of width. now i can set top fragment width match_parent, do you want something like this?

**Comment by dangalg** [comment]
Its easy to fix..
בתאריך 18 בדצמ 2014 07:27, מאת "vuhung3990" notifications@github.com:

**Comment by vuhung3990** [comment]
good job @dangalg , i spent much time to fix it

**Comment by pedrovgs** [comment]
Guys? How is this issue. Have you already fixed this? I'm waiting for your PR.

**Comment by pedrovgs** [comment]
@Fiddl3 are you working on this? What's the state of this feature?

**Comment by Fiddl3** [comment]
Now I'm working on my engineering degree (Home automation project) and I don't have any time for this. I hope in second half of February this'll change.

**Comment by pedrovgs** [comment]
Ok! Good luck with your personal project!!!

**Comment by ScottCooper92** [comment]
Hey @Fiddl3  did you ever get around to implementing this and sending a pull request?
